### ISSUE TITLE
Comments Table DELETE Comment Call

### ISSUE THREAD

**Issue by Jayoussef28** [asparadise33/rare_tres_amigos_plus_one#23]
## 🧑 Story
Create API request to delete a single Comment

## 🔨 Acceptance Criteria

- [x]  export the call in the init.py
- [x]  request_handler.py file connect, with an if else statement
- [x]  create a sql query to delete a single comment
- [x]  test in postman for 204 response, and rerun the GET call to make sure comment has been deleted

.

## 📚 Resources
![image](https://github.com/user-attachments/assets/3f103c77-bf97-4231-bc88-1e15a902ac1f)

**Comment by NelsonOlivierNgaleumo** [comment]
Completed
